# Generated by Django 2.2.7 on 2020-05-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioncore', '0008_auto_20200514_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='next_bet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
