# Generated by Django 2.2.7 on 2020-05-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioncore', '0012_auto_20200514_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='increment',
            field=models.IntegerField(blank=True, choices=[(1, '1%'), (2, '2%'), (3, '3%'), (4, '4%'), (5, '5%')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
