# Generated by Django 2.2.7 on 2020-05-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioncore', '0013_auto_20200518_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
