# Generated by Django 2.2.7 on 2020-05-18 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioncore', '0014_auto_20200518_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 18, 23, 55, 28, 372460), null=True),
        ),
    ]
