# Generated by Django 2.2.7 on 2020-05-19 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioncore', '0015_auto_20200518_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 19, 14, 51, 53, 694616), null=True),
        ),
    ]
