# Generated by Django 2.2.7 on 2020-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioncore', '0016_auto_20200519_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='increment',
            field=models.IntegerField(choices=[(1, '1%'), (2, '2%'), (3, '3%'), (4, '4%'), (5, '5%')], default=1),
        ),
    ]
