# Generated by Django 2.2.7 on 2020-05-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioncore', '0017_auto_20200519_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='som',
            field=models.IntegerField(choices=[(1, 'som'), (2, '$')], default=1),
        ),
    ]
