# Generated by Django 2.2.7 on 2020-05-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioncore', '0018_auction_som'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='som',
            field=models.CharField(choices=[('som', 'som'), ('$', '$')], default='som', max_length=10),
        ),
    ]
