# Generated by Django 2.2.7 on 2020-05-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200513_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер телефона'),
        ),
    ]
