# Generated by Django 2.2.7 on 2020-05-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='star',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
