# Generated by Django 2.2.7 on 2020-05-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_auto_20200522_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
