# Generated by Django 2.2.7 on 2020-05-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
