# Generated by Django 2.2.7 on 2020-05-22 21:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0008_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_ky',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_ky',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
