# Generated by Django 2.2.7 on 2020-06-25 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctioncore', '0019_auto_20200519_1940'),
        ('banner', '0011_auto_20200525_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctioncore.Auction'),
        ),
    ]
